version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: '[npm] '
    groups:
      minor-patch-updates:
        update-types: ['minor', 'major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: '[actions] '
    groups:
      minor-patch-updates:
        update-types: ['minor', 'major']
